spring:
 application:
   name: ReportGenerationApp

 datasource:
   url: jdbc:mysql://localhost:3306/res_appdb
   username: root
   password: Test
   driver-class-name: com.mysql.cj.jdbc.Driver

 jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

 mvc:
  view:
    prefix: /WEB-INF/
    suffix: .jsp

 mail:
   host: smtp.gmail.com
   port: 587
   username: enter your Email
   password: enter your app password
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true